### ISSUE TITLE
datatools.constants is missing when importing gpstools.py

### ISSUE THREAD

**Issue by cctrunz** [jzmejia/datatools#5]
Hi Jess! when I import gpstools i get the error message that datatools.constants is missing on line 24. Its to import seconds_per_day, 
I fixed this issue by commenting the line 24 in gpstools, but I don't know if this is going to affect other functions.

**Comment by jzmejia** [comment]
thanks! it looks like I don't have that file anymore. I'll try to fix it and check what is using this value
